apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-config
  namespace: kube-system
data:
  registry-config.yaml: |
    mirrors:
      localhost:5000:
        endpoint:
          - "http://localhost:5000"
    configs:
      localhost:5000:
        tls:
          insecure_skip_verify: true



